#!/bin/bash

export PYTHONPATH=${PYTHONPATH}
export MCP_SERVER_PORT=${MCP_SERVER_PORT}
export AIRFLOW_API_URL=${AIRFLOW_API_URL}
export AIRFLOW_API_USERNAME=${AIRFLOW_API_USERNAME}
export AIRFLOW_API_PASSWORD=${AIRFLOW_API_PASSWORD}
export AIRFLOW__WEBSERVER__EXPOSE_CONFIG=${AIRFLOW__WEBSERVER__EXPOSE_CONFIG}
export AIRFLOW_LOG_LEVEL=${AIRFLOW_LOG_LEVEL}

python -m mcp_airflow_api.airflow_api
